### ISSUE TITLE
Ps Vita. Pfba loads default emulation settings for games ignoring user custom ones.

### ISSUE THREAD

**Issue by DerinQyu** [Cpasjuste/pfba#27]
Device: Ps Vita Fat
Version of firmware: 3.60
Version of Pfba: happens on both 1.52 & 1.54

Hi, I was on 1.51 then updated to 1.52 then to 1.54 and this happens:

## Issue one:

- On fresh install, go to main emulator settings change something like full screen and save.
- Custom settings apply to all games fine until you exit the emulator.
- Open the emulator again and load any game without touching the emulator settings, the emulator loads the default settings instead of the custom ones created by the user.
- On ux0/data/pfba conf file still has the custom changes, so it must be something else.

## Issue two:

- If you make a per game configuration, it applies to all games.
- For example, on street fighter third strike turn on frameskip and i will work as expected, exit the game and load another game, frame skip is on for all games when it shouldn't untill you exit the emulator.

Above issues doesn't happen on ver 1.51.

Can't test if this happens in the switch port too.

**Comment by Cpasjuste** [comment]
Hi, fixed in 4300a9a4422cff66448fbd508bd89a3c9051b874 (will release that in a few days). Thanks for the report !
