### ISSUE TITLE
Duplicate name issue in previews & titles pics

### ISSUE THREAD

**Issue by oORSXOo** [Cpasjuste/pfba#37]
Device: Nintendo Switch [4.1.0]
HBL: Homebrew Menu (hbmenu)

Issue:
Not arcade Previews & titles pics (Megadrive, pce, coleco, ...) doesn't display anymore when there is a prefix in the filename.
Sadly, there are some games across all emulated platforms with the same .zip name and the same .png name.
Since all the pics are in the same folder, some are overwritten.

**Comment by Cpasjuste** [comment]
Hi, you need to add the console prefix to your preview pics (for example "md_sonic.png" for sonic megadrive).
